version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "build(dependency): ⬆️"
      prefix-development: "build(ci-dependency): ⬆️"
    labels:
      - "ci"
      - "github_actions"
      - "dependencies"
