name: Tests
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags-ignore: ["**"]
  pull_request:
  schedule:
    - cron: "0 1 * * *"

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: just ${{ matrix.receipt }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python:
          - "3.13"
        tox_env:
          - pre-commit
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install uv
        uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174 # v5
      - name: Install just
        uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2
      - name: Run the test suite
        run: |
          just ${{ matrix.receipt }}
  test:
    name: Run ${{ matrix.diffusion }} tests under python ${{ matrix.python }} on ${{ matrix.os }}
    needs: check
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        python:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        diffusion:
          - open-source
          - proprietary
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install uv
        uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174 # v5
      - name: Install just
        uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2
      - name: Run the test suite
        run: |
          just test-${{ matrix.diffusion }} ${{ matrix.python }}
